name: 'Install Swiftly'
description: 'Automatically install swiftly and the selected Swift toolchain.'
branding:
  icon: 'download'
  color: 'orange'

runs:
  using: 'composite'
  steps:
    - name: 'Install Swiftly (macOS)'
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        curl -O https://download.swift.org/swiftly/darwin/swiftly.pkg
        installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
        ~/.swiftly/bin/swiftly init --quiet-shell-followup --skip-install
        . ${SWIFTLY_HOME_DIR:-~/.swiftly}/env.sh
        echo "SWIFTLY_HOME_DIR=${SWIFTLY_HOME_DIR}" >> "${GITHUB_ENV}"
        echo "SWIFTLY_BIN_DIR=${SWIFTLY_BIN_DIR}" >> "${GITHUB_ENV}"
        echo "${SWIFTLY_BIN_DIR}" >> "${GITHUB_PATH}"
    - name: 'Install Swiftly (Linux)'
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        curl -O "https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz"
        tar zxf "swiftly-$(uname -m).tar.gz"
        ./swiftly init --quiet-shell-followup --skip-install
        . ${SWIFTLY_HOME_DIR:-~/.local/share/swiftly}/env.sh
        echo "SWIFTLY_HOME_DIR=${SWIFTLY_HOME_DIR}" >> "${GITHUB_ENV}"
        echo "SWIFTLY_BIN_DIR=${SWIFTLY_BIN_DIR}" >> "${GITHUB_ENV}"
        echo "${SWIFTLY_BIN_DIR}" >> "${GITHUB_PATH}"
    - name: 'Install .swift-version Toolchain'
      shell: bash
      run: |
        if [ -f .swift-version ]; then
          swiftly install --assume-yes --post-install-file=swiftly-post-install.sh
          if [ -f swiftly-post-install.sh ]; then
            sudo bash -c ". swiftly-post-install.sh"
            rm swiftly-post-install.sh
          fi
        fi
